name: build
on:
  - workflow_call
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
        with:
          version: "1.7" # Github's runners still use 1.6 as of writing.
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make executable
        run: chmod +x ./*.sh
      - name: Build
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./*.zip
